@startuml
!include https://raw.githubusercontent.com/alextheartisan/plantuml-themes/master/src/themes/pretty.iuml

left to right direction
hide empty members

class N as "Note"
class NT as "Note Title"
class NC as "Note Controls"
class NR as "Note Representation"

class MP as "Markdown Processor"

N -- MP

NR -- N
N -- NC
N -- NT
@enduml
