@startuml

!include https://raw.githubusercontent.com/alextheartisan/plantuml-themes/master/src/themes/pretty.iuml

left to right direction

hide empty members

class BL as "Builder" <<(C, pink)>>
class AF as "Abstract Factory" <<(C, pink)>>
class FM as "Factory Method" <<(C, pink)>>
class PT as "Prototype" <<(C, pink)>>
class SN as "Singleton" <<(C, pink)>>

class A  as "Adapter" <<(S, lightgreen)>>
class BR as "Bridge" <<(S, lightgreen)>>
class CS  as "Composite" <<(S, lightgreen)>>
class D  as "Decorator" <<(S, lightgreen)>>
class FC as "Facade" <<(S, lightgreen)>>
class FL as "Flyweight" <<(S, lightgreen)>>
class PX as "Proxy" <<(S, lightgreen)>>

class CR as "Chain of Responsibility" <<(B, lightblue)>>
class CM as "Command" <<(B, lightblue)>>
class I  as "Iterator" <<(B, lightblue)>>
class MD as "Mediator" <<(B, lightblue)>>
class MM as "Memento" <<(B, lightblue)>>
class O  as "Observer" <<(B, lightblue)>>
class ST as "State" <<(B, lightblue)>>
class SR as "Strategy" <<(B, lightblue)>>
class TM as "Template Method" <<(B, lightblue)>>
class V  as "Visitor" <<(B, lightblue)>>

CM --> CS
CM --> MM


CS --> FL
FL <- SR
D <--> SR
CS -> D
V <- CS

CS --> I
V --> I

I --> MM

CR --> CS

CS ---> BL
'CS --> V
'ST -> FL
TM --> SR
TM --> FM
AF --> FM
AF --> PT
AF --> SN
FC --> SN
ST -> FL
O --> MD
@enduml
