import { FONT_SIZES, STROKE_SIZES, LABEL_FONT_SIZES } from 'tldraw';

FONT_SIZES.s = 16;
FONT_SIZES.m = 20;
FONT_SIZES.l = 24;
FONT_SIZES.xl = 28;

STROKE_SIZES.s = 2;
STROKE_SIZES.m = 2;
STROKE_SIZES.l = 4;
STROKE_SIZES.xl = 8;

LABEL_FONT_SIZES.s = 14;
LABEL_FONT_SIZES.m = 18;
LABEL_FONT_SIZES.l = 22;
LABEL_FONT_SIZES.xl = 26;
// ARROW_LABEL_FONT_SIZES.s = 10;
