@startuml

!include https://raw.githubusercontent.com/alextheartisan/plantuml-themes/master/src/themes/pretty.iuml

hide empty members

left to right direction

class Aside
'class Tiddly {}
class Canvas
'class Tufte
@enduml
