@startuml

!include https://raw.githubusercontent.com/alextheartisan/plantuml-themes/master/src/themes/pretty.iuml

hide empty members
left to right direction
package notes.canvas {
    package @types {
        class Position {
            {static} Zero
            x: number
            y: number
        }
    }

    package components {
        class CanvasPage {
        }
        class DragLayer {
        }

        class DraggableNote {
        }

        class NoteDragPreview {
        }
        class Note {}

        CanvasPage <-- DragContainer
        CanvasPage <-- DragLayer
        DraggableNote <-- Note
        NoteDragPreview <-- Note
        DragContainer <-- DraggableNote
        DragLayer <-- NoteDragPreview
    }
}

/'
class MarkdownService {
    configure()
    process()
}

package notes {
    class NoteService {
        getNote()
        getProcessedNote()
    }
}

package notes.canvas {

    package services {
        class LayoutService {
            getScrollingPosition(): Position
            setScrollingPosition(pos: Position): void

            getAllPositions(): Record<NoteId, Position>
            getPosition(id: NoteId): Position
            setPosition(id: NoteId, pos: Position): void
        }
    }
}
'/
@enduml
